import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFile} from 'node:fs/promises';
const html=await readFile(new URL('../admin.html',import.meta.url),'utf8');
for (const match of html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g)) if(match[1].trim())new vm.Script(match[1]);
assert.match(html,/preloadPublicBrand\(\);\s*publicHealth\(\)/,'Admin startup must initialize public branding');
const lines=html.split('\n');
const get=(prefix)=>{const line=lines.find(x=>x.startsWith(prefix));assert.ok(line,prefix);return line};
const definitions=['const MODULE_DEFAULTS=','function effectiveModules','function moduleEnabled','async function moduleCache','function moduleValues','window.saveModules=','window.saveSystemModules=','window.setTicketOrder=','window.saveProducer=','VIEWS.work='].map(get).join('\n');
const S={cache:{config:{branding:{name:'BeatPlay'},modules:{union:false,marketplace:false,ticketing:false,custom:false}}}};
const fields={main:{innerHTML:''}};
let calls=[],saved;
const context={window:{},VIEWS:{},S,obj:v=>v&&typeof v==='object'&&!Array.isArray(v)?v:{},arr:v=>Array.isArray(v)?v:[],$:k=>fields[k]||null,cache:async(k,fn)=>fn(),api:async(path,opt)=>{calls.push({path,opt});return[]},
 saveJSON:async(path,data)=>{saved=data},closeModal(){},renderNav(){},go(){},toast(){},renderProducers(){},nowId:()=> 'p1',head:()=>'',stat:()=>'',esc:v=>v,table:()=>''};
vm.createContext(context);vm.runInContext(definitions,context);
assert.equal(vm.runInContext('moduleEnabled("union")',context),false);
S.cache.config.modules.union='false';
assert.equal(vm.runInContext('moduleEnabled("union")',context),false,'non-boolean flags do not opt in');
await vm.runInContext('moduleCache("marketplace","market","admin/marketplace/requests",false)',context);
assert.equal(calls.length,0,'disabled modules must not call API');
S.cache.config.modules={union:false,marketplace:true,ticketing:true,events:false,custom:false};
assert.equal(vm.runInContext('moduleEnabled("ticketing")',context),false,'ticketing requires events');
for(const [key,value] of Object.entries({artists:'true',radio:'true',podcasts:'true',iptv:'true',events:'true',jobs:'true',marketplace:'false',ticketing:'false',pro:'true',ads:'true',union:'false'}))fields['sysmod_'+key]={value};
await context.window.saveSystemModules();
assert.equal(saved.branding.name,'BeatPlay');assert.equal(saved.modules.custom,false,'preserve unrecognized future flags');assert.equal(saved.modules.ticketing,false);
const before=S.cache.config;context.saveJSON=async()=>{throw Error('offline')};
await assert.rejects(context.window.saveSystemModules(),/offline/);assert.equal(S.cache.config,before,'failed save leaves cached config intact');
context.saveJSON=async(path,data)=>{saved=data};
S.cache.ticketOrders=[{id:'t1',payment_status:'pending'}];
await context.window.setTicketOrder(0,'confirmed');
assert.equal(calls.at(-1).opt.body.payment_status,'pending','confirming interest is not collecting payment');
S.cache.producers=[{id:'p1',nombre:'Productora',convenio:true}];
for(const [key,value] of Object.entries({pName:'Productora',pEmail:'',pWhatsapp:'',pContact:'',pCity:'Rosario',pProvince:'Santa Fe',pNotes:''}))fields[key]={value};
await context.window.saveProducer(0);
assert.equal(saved[0].convenio,true,'hidden institutional field must not crash or erase existing data');
S.cache.config.modules={jobs:true,marketplace:false,union:false,ticketing:false};calls=[];
await context.VIEWS.work(false);
assert.equal(calls.some(x=>/cct|marketplace|ticketing|contrataciones/.test(x.path)),false);
assert.equal(fields.main.innerHTML.includes('CCT'),false);
assert.equal(fields.main.innerHTML.includes('Solicitudes de entradas'),false);
console.log('PASS: Admin module persistence, disabled requests, ticket state and productora without institutional control');
