import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
const source=await readFile(new URL('../worker.js',import.meta.url),'utf8');const {default:worker,uadavArtistHandle}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
assert.equal(uadavArtistHandle('@DJMarkus'),'djmarkus');for(const v of ['ab','admin','uadavsantafe','bad space','<script>','áéí',null])assert.equal(uadavArtistHandle(v),'');
const aliases=new Map(),current=new Map(),kv=new Map([['artistas',JSON.stringify([{id:'a1',nombre:'Gratis'},{id:'a2',nombre:'Otro'}])],['artist_access_TEST_FREE_ARTIST_123',JSON.stringify({artist_id:'a1',expires:Date.now()+60000})],['artist_access_TEST_OTHER_ARTIST_123',JSON.stringify({artist_id:'a2',expires:Date.now()+60000})]]);let race=false;
const env={UADAV_DB:{get:async k=>kv.get(k)||null},DB:{prepare(sql){let a=[];return{bind(...args){a=args;return this},async first(){if(sql.includes('FROM artist_handles'))return aliases.has(a[0])?{artist_id:aliases.get(a[0])}:null;if(sql.includes('FROM artist_current_handles'))return current.has(a[0])?{handle:current.get(a[0])}:null;return null},async all(){return {results:[]}},async run(){if(sql.startsWith('CREATE'))return {meta:{changes:0}};if(sql.startsWith('INSERT OR IGNORE INTO artist_handles')){if(race){aliases.set(a[0],'a2');race=false}if(aliases.has(a[0]))return {meta:{changes:0}};aliases.set(a[0],a[1]);return {meta:{changes:1}}}if(sql.startsWith('INSERT INTO artist_current_handles')){if(aliases.get(a[2])!==a[3])return {meta:{changes:0}};current.set(a[0],a[1]);return {meta:{changes:1}}}return {meta:{changes:0}}}}},async batch(stmts){const out=[];for(const stmt of stmts)out.push(await stmt.run());return out}}};
async function req(path,method='GET',body,token='TEST_FREE_ARTIST_123'){const r=await worker.fetch(new Request('https://test.example/api/'+path,{method,headers:token?{Authorization:'Bearer '+token}:{},...(body?{body:JSON.stringify(body)}:{})}),env,{});return {status:r.status,data:await r.json()}}
assert.equal((await req('artist/handle','GET',null,'')).status,401);assert.equal((await req('artist/handle')).data.handle,'');assert.equal((await req('artist/handle','PUT',{handle:'DJMarkus'})).status,200);assert.equal((await req('artist/handle')).data.handle,'djmarkus');assert.equal((await req('artist/handle','PUT',{handle:'djmarkus'},'TEST_OTHER_ARTIST_123')).status,409);
assert.equal((await req('artist/handle','PUT',{handle:'markusradio'})).status,200);for(const h of ['djmarkus','markusradio'])assert.equal((await req('public/artist-handle?handle='+h,'GET',null,'')).data.artist_id,'a1');
assert.equal((await req('artist/handle','PUT',{handle:'admin'})).status,400);race=true;assert.equal((await req('artist/handle','PUT',{handle:'race-name'})).status,409);assert.equal(current.get('a1'),'markusradio');
kv.set('artistas',JSON.stringify([{id:'a1',nombre:'Gratis',visible:false},{id:'a2',nombre:'Otro'}]));assert.equal((await req('public/artist-handle?handle=djmarkus','GET',null,'')).status,404);kv.set('artist_access_TEST_FREE_ARTIST_123',JSON.stringify({artist_id:'a1',expires:1}));assert.equal((await req('artist/handle')).status,401);
console.log('PASS: free artist handles, reserved names, owner auth, uniqueness race, preserved aliases, hidden profile and expiry');
