import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {webcrypto,createECDH,hkdfSync,createDecipheriv} from 'node:crypto';import {sqliteD1} from './sqlite-d1.mjs';globalThis.crypto||=webcrypto;
const source=await readFile(new URL('../worker.js',import.meta.url),'utf8'),{default:worker}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64')),DB=sqliteD1(),map=new Map(),env={DB,ADMIN_KEY:'admin',UADAV_DB:{get:async k=>map.get(k)||null,put:async(k,v)=>map.set(k,v),delete:async k=>map.delete(k)}},a='UAC-'+'a'.repeat(64),b='UAC-'+'b'.repeat(64);let serial=0;
async function call(path,method='GET',body,auth=a){const r=await worker.fetch(new Request('https://test.invalid/api/'+path,{method,headers:{Origin:'https://uadavstream.com.ar',Authorization:'Bearer '+auth,'Content-Type':'application/json','CF-Connecting-IP':'ip'+(++serial)},...(body?{body:JSON.stringify(body)}:{})}),env,{});return{status:r.status,data:await r.json()}}
const originalFetch=globalThis.fetch,ecdh=createECDH('prime256v1');ecdh.generateKeys();const auth=Buffer.alloc(16,9),subscription={endpoint:'https://fcm.googleapis.com/fcm/send/fake-test',keys:{p256dh:ecdh.getPublicKey().toString('base64url'),auth:auth.toString('base64url')}};let sent=[];
globalThis.fetch=async(url,options)=>{assert.equal(url,subscription.endpoint);sent.push(options);return{status:201}};
try{await call('account','POST',{data:{}});await call('account','POST',{data:{}},b);assert.equal((await call('admin/push','POST')).status,401);assert.equal((await call('admin/push','POST',{},'admin')).status,200);const settings=(await call('account/push')).data;assert(settings.enabled);assert(!JSON.stringify(settings).includes('private'));await call('admin/push','POST',{},'admin');assert.equal((await call('account/push')).data.public_key,settings.public_key);
assert.equal((await call('account/push','POST',{...subscription,endpoint:'https://127.0.0.1/test'})).status,400);assert.equal((await call('account/push','POST',subscription)).status,200);const aid=(await DB.prepare('SELECT account_id FROM audience_push_subscriptions').first()).account_id;
const msg=await call('admin/announcements','POST',{title:'SECRET TITLE',message:'PRIVATE MESSAGE',account_id:aid,push:true},'admin');assert.equal(msg.status,200,JSON.stringify(msg));assert.equal(sent.length,1);const request=sent[0],body=Buffer.from(request.body),salt=body.subarray(0,16),as=body.subarray(21,86),encrypted=body.subarray(86),shared=ecdh.computeSecret(as),ikm=Buffer.from(hkdfSync('sha256',shared,auth,Buffer.concat([Buffer.from('WebPush: info\0'),ecdh.getPublicKey(),as]),32)),cek=Buffer.from(hkdfSync('sha256',ikm,salt,Buffer.from('Content-Encoding: aes128gcm\0'),16)),nonce=Buffer.from(hkdfSync('sha256',ikm,salt,Buffer.from('Content-Encoding: nonce\0'),12)),decipher=createDecipheriv('aes-128-gcm',cek,nonce);decipher.setAuthTag(encrypted.subarray(-16));const plain=Buffer.concat([decipher.update(encrypted.subarray(0,-16)),decipher.final()]);assert.equal(plain.at(-1),2);const payload=JSON.parse(plain.subarray(0,-1));assert.equal(payload.path,'/usuario.html');assert(!JSON.stringify(payload).includes('PRIVATE'));assert(!JSON.stringify(payload).includes('SECRET'));const jwt=request.headers.Authorization.match(/t=([^,]+)/)[1].split('.'),pub=await crypto.subtle.importKey('raw',Buffer.from(settings.public_key,'base64url'),{name:'ECDSA',namedCurve:'P-256'},false,['verify']);assert(await crypto.subtle.verify({name:'ECDSA',hash:'SHA-256'},pub,Buffer.from(jwt[2],'base64url'),Buffer.from(jwt[0]+'.'+jwt[1])));assert.equal(JSON.parse(Buffer.from(jwt[1],'base64url')).aud,'https://fcm.googleapis.com');
await call('admin/push','PUT',{},'admin');assert.equal(sent.length,1);await call('account/push','DELETE');await call('admin/announcements','POST',{title:'After unsubscribe',message:'No push',push:true},'admin');assert.equal(sent.length,1);assert.equal((await call('admin/artist-inquiries','PATCH',{id:'missing',estado:'cerrada'},'admin')).status,404);console.log('PASS: authenticated subscriptions, SSRF rejection, stable server-only keys, independent RFC8291 decryption, VAPID signature, private generic payload, no repeat delivery and unsubscribe');}finally{globalThis.fetch=originalFetch;DB.close()}
